spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adivinalapalabra
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
      cors:
    allowed-origins: "http://localhost:8080"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"
jwt:
  secret: adivinaLaPalabraGrupo2Sopra
  expiration: 900
dates:
  timezone: Europe/Madrid
security:
  allowed-routes: /auth/**
